name: CI

on:
  push:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 8.0]

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-dist --no-suggest --no-interaction --no-scripts

      - name: Check codestyle
        run: vendor/bin/ecs check --config=dev/easy-coding-standard.yml --no-progress-bar .

      - name: Execute unit tests
        run: vendor/bin/phpunit --testdox --colors=always --coverage-text=report/coverage.txt

      - name: Archive code coverage results
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: report/coverage.txt

      - name: Report coverage in PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: slavcodev/coverage-monitor-action@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "logs/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
